name: fools_gold
dependencies:
  - python==3.9.19
  - ipython
  - alpaca-py==0.31.0
  - ipykernel
  - tqdm
  - s3fs
  - boto3
  - pyarrow
  - fastparquet
  - matplotlib 
  - pyyaml
  - scikit-learn
  - xgboost
  - openpyxl
  - xlsxwriter