s3_bucket: 'sisyphus-general-bucket'
base_folder: 'AthenaInsights'

data_folder: 'latest_data'

csv_folder: 'csv'
parquet_folder: 'parquet'
data_prep_folder: 'data_prep'
reduced_autocorelation_folder: 'reduced_autocorelation'
feature_prep_folder: 'feature_prep'

model_base_folder: 'model'
model_data_folder: 'data'
model_results_folder: 'results'
model_results_images_subfolder: 'images'
model_results_texts_subfolder: 'texts'